[package]
name = "asm_rs_bench"
version = "0.1.0"
edition = "2021"

[dependencies]
half = "2.4.1"
rand = "0.8.5"
rayon = "1.10.0"
wide = "0.7.28"

[[bin]]
name = "gemv"
path = "src/gemv.rs"

[[bin]]
name = "gemm"
path = "src/gemm.rs"
